# Generated by Django 5.2.12 on 2026-03-12 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='featured_image',
            field=models.ImageField(blank=True, null=True, upload_to='job_images/'),
        ),
    ]
