# Generated by Django 5.2.12 on 2026-03-12 17:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_job_featured_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('icon', models.CharField(blank=True, help_text='Tailwind icon class or SVG string', max_length=50)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('DEPOSIT', 'Deposit to Escrow'), ('RELEASE', 'Release to Worker'), ('REFUND', 'Refund to Provider'), ('WITHDRAW', 'Withdrawal'), ('PROMOTION', 'Self Promotion Bid')], max_length=20),
        ),
        migrations.AddField(
            model_name='job',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='core.category'),
        ),
        migrations.CreateModel(
            name='PromotedWorker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promotion_bid', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('clicks', models.PositiveIntegerField(default=0)),
                ('promoted_at', models.DateTimeField(auto_now=True)),
                ('worker', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='promotion', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
