# Generated by Django 5.2.12 on 2026-03-12 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_customuser_user_type_offlineservice_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='offlineservice',
            name='closing_time',
            field=models.TimeField(default='17:00:00', help_text='e.g. 17:00:00'),
        ),
        migrations.AddField(
            model_name='offlineservice',
            name='opening_time',
            field=models.TimeField(default='09:00:00', help_text='e.g. 09:00:00'),
        ),
    ]
