# Generated by Django 5.2.12 on 2026-03-13 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_cart_cartitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='offlinebooking',
            name='customer_phone',
            field=models.CharField(default='0000000000', help_text='Contact number for the provider', max_length=20),
            preserve_default=False,
        ),
    ]
